spring.application.name=financeflow-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:financeflow}?sslmode=${PGSSLMODE:require}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.chave-secreta=${JWT_SECRET:financeflow-chave-secreta-de-desenvolvimento-min-32-bytes}
jwt.expiracao-ms=28800000
